### ISSUE TITLE
`.doc-*` Layout and Mobile

### ISSUE THREAD

**Issue by sjhcockrell** [meetup/sassquatch#54]
Tagging @unjust, @akdetrick.

**Problem**

One of the things we have kicked around and never really resolved was the issue of layout in single-column environments with "full bleed" (100% width) boxes.

Here's what seems to be the core defaults of existing components:

`.doc-box`
- Borders on all sides.
- Border color
- Border radius
- Bottom margin
- White Background

`.doc-content`
- Nesting selector rules when combined with doc-box
- Transparent bottom border (?)
- Padding `$baseline`, except on bottom

`.doc-padding`
- Transparent bottom border (?)
- Padding `$baseline`, except on bottom.

What doesn't quite work out well for single-column, fix-flex (vertical-centered) layout environments we'll probably see more and more of. 

Here are the defaults that seem to cause problems:

`.doc-box`
- Borders on all four sides
- Border radius

`.doc-content`/`.doc-padding`
- Transparent bottom border (seems like it could be removed?)
- Non-$baseline bottom padding

**Questions**
1. Does it seem reasonable to create mobile-layout specific modifiers in the long run, in which we are overriding the Sassquatch-standard definitions?

Example:

``` css
.doc-box--full {
  @extend .doc-box;
  border-left: none;
  border-right: none;
  border-radius: 0;
}
```
1. Does it make sense to override/redefine problematic selectors?

Example:

``` css
// Within mobile sassquatch scope:
.doc-content {
  padding: $baseline;
  border-bottom: none;
}
```
1. Does it make sense to create a differently-behaved `.doc-*` standard, or re-examine the existing defaults?

One potential (half-baked) proposal, would be to have a `.doc-card` class that behaved like a doc-box, but with consistently-enforceable rules for transitioning between full-bleed and card-like layouts based on media queries and/or modifier classes. 

It would be _extremely_ similar to doc-box, but it wouldn't inherit any potential cascade baggage of `.doc-box`/`.doc-padding` that would need to be redefined/overruled in mobile stylesheets.
